export class PorductList {
  productId: number;
  name: string;
  nameEn: string;
  highlight: string;
  highlightEn: string;
  description: string;
  descriptionEn: string;
  imageurl: string;
  imageurl2: string;
  imageurl3: string;
  imageurl4: string;
  imageurl5: string;
  pricelist: number;
  specialPrice: number;
  category3Id: number;
  category3Name: string;
  category2Id: number;
  category2Name: string;
  category1Id: number;
  category1Name: string;
  productbrandId: number;
  brandname: string;
  sku: string;
  aliasName: string;
  weight: number;
  dimensionswidth: number;
  dimensionslength: number;
  dimensionsheight: number;
  constructor() {}
}
